sudo: required
services:
  - docker

before_install:
  - docker build -t kirukarki/react-client-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true kirukarki/react-client-test npm run test -- --coverage

after_success:
  - docker build -t kirukarki/react-client ./client
  - docker build -t kirukarki/nginx ./nginx
  - docker build -t kirukarki/server ./server
  - docker build -t kirukarki/worker ./worker

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push images to Docker Hub
  - docker push kirukarki/react-client
  - docker push kirukarki/nginx
  - docker push kirukarki/server
  - docker push kirukarki/worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-568516007683
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY