sudo: required
services:
  - docker

before_install:
  - docker build -t kirukarki/react-client-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true kirukarki/react-client-test npm run test -- --coverage

after_success:
  - docker build -t kirukarki/react-client ./client
  - docker build -t kirukarki/nginx ./nginx
  - docker build -t kirukarki/server ./server
  - docker build -t kirukarki/worker ./worker

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push kirukarki/react-client
  - docker push kirukarki/nginx
  - docker push kirukarki/server
  - docker push kirukarki/worker